version: '3.8'

services:
  movie-awards-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: movie-awards-app
    ports:
      - "8888:80"
    restart: always    
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true